### ISSUE TITLE
A button to create a new note

### ISSUE THREAD

**Issue by Taitava** [graydon/obsidian-dangling-links#11]
Hi,

in the list of dangling links, I think there could be a button for creating that particular missing note. It would work the same way as clicking a non-exiting link in Obsidian's preview mode. After a new note is created, it will be opened.

Ctrl+clicking the button would create the note and open it in a new pane.

Thanks! :)

**Comment by claremacrae** [comment]
Thanks for the suggestion.

> It would work the same way as clicking a non-exiting link in Obsidian's preview mode.

_I've been given collaborator permissions on this project, so that I can review the issues, and potentially fix one or two things later on._

### Current facility to achieve what is requested

In case anyone reading this doesn't know....

The way to do this currently is to:

1. click on the filename link in the Dangling Links pane
    <img width="625" alt="image" src="https://github.com/graydon/obsidian-dangling-links/assets/4840096/a2205a9e-a4ce-460b-b8f9-0237394fbe3a">
3. Make sure Obsidian is in Reading mode
4. Click or Command/Control click on the link, to make Obsidian create the file.

### Challenges with implementing this

This request is actually rather harder than it seems at first glance.

Suppose you have multiple dangling links to the same missing file name, in files that are in different folders.

Where the new note is created depends on the location of the file you are viewing when you click on the non-existing link.

### Conclusion

So because this request is asking for the plugin to duplicate functionality that is already provided by Obsidian, I'm going to close it, as not a priority to spend volunteer time on.
