### ISSUE TITLE
Request for deleting danglink links (ideally based on sub-folders)

### ISSUE THREAD

**Issue by santiyounger** [graydon/obsidian-dangling-links#4]
I got a workflow idea for task that wouldn't be possible without this plugin, so thank you for making this.

Long story short, I have links to exisiting files in a tasks folder, each task is a note, an individual .md file  after I complete a task I move it out of the vault.

This means that I have a lot of [[links]] pointing at files that are no longer there. 

This amazing plugin allows me to quickly indentify them.

Since I have to delete them manually, I'd love to know if it where possible to automatically delete the detected dangling links.

This would be even better if it could be restricted to an specific sub-folder as mentioned in this other request https://github.com/graydon/obsidian-dangling-links/issues/3

Thank you, I really appreciate your work, and would love to know if this could be  possible

**Comment by claremacrae** [comment]
_I've been given collaborator permissions on this project, so that I can review the issues, and potentially fix one or two things later on._

I understand the suggestion, but:

1. Writing any code that removes text from a user's notes is a great responsibility. Bugs cause damage.
2. Regarding "This would be even better if it could be restricted to an specific sub-folder as mentioned in this other request", adding configuration options to a plugin is a non-trivial amount of work, and then the feature needs to be documented and maintained forever.

The current alternative options are available to remove dangling links one does not intend to fix:

1. Click on the filename in the Dangling Links pane to navigate to the location, and delete the text
2. There are several plugins that offer find-and-replace facilities: https://obsidian.md/plugins?search=replace

In view of the risks, and the alternative options available, and the number of other requests here, I'll close this request.
